### PR TITLE
Fix error when installing with CLI

### PR DESCRIPTION
**Pull request by rubencm**
This fixes this error when triying to install the extension with CLI.

`PHP Fatal error:  Uncaught Error: Call to undefined function david63\sitelogo\adm_back_link() in /XXX/phpBB3/ext/david63/sitelogo/ext.php:37`

### CODE REVIEW

**Comment by david63** [comment]
Sorry but that pull request is not acceptable

**Comment by rubencm** [comment]
What is wrong with it?

**Comment by david63** [comment]
Everything.

Just because there is a "problem" in one area you do not go around deleting code that is required in another area and will impact on the majority of users. Also I am not sure why you need to install extensions using CLI, or even if the installation of extensions via CLI is fully supported.

I am not saying that the problem should not be addressed - but this is not the way to do it.

**Comment by rubencm** [comment]
Well, i have fixed it form me, and now meet my needs.

I think you are worng, although it worked on the web interface, you can't add html there, that function should only return true or false, acording with phpbb documentation here: https://area51.phpbb.com/docs/dev/32x/extensions/tutorial_advanced.html#using-installation-commands-in-ext-php
About the language string, it is only used there.

**Pull request closed without merging**
